# Generated by Django 3.2.8 on 2023-02-13 15:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("TODO", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="opened",
            field=models.BooleanField(default=True),
        ),
    ]
